version: '3'

services:
  elrond:
    build:
      context: ./
      dockerfile: ./docker/elrond/Dockerfile

    command: bash -c "go run cmd/node/main.go -port 4000 -max-allowed-peers 4 -private-key \"ZBis8aK5I66x1hwD+fE8sIw2nwQR5EBlTM8EiAOLZwE=\""
    ports:
      - 8080:8080

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.name=elrond-cluster
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=es01,es02
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata/node1:/usr/share/elasticsearch/data
      - ./docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
#    networks:
#      - elrond

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.name=elrond-cluster
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=es01,es02
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata/node2:/usr/share/elasticsearch/data
      - ./docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      #- SERVICES=${SERVICES- }
      - SERVICES=kinesis
      - DEBUG=1
      - DATA_DIR=./tmp/localstack
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

#   networks:
#     - elrond
  filebeat:
    build: docker/filebeat
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      LOGSTASH_PORT: ${LOGSTASH_PORT}
      INDEX: ${ELASTIC_INDEX}
    volumes:
    - ./docker/filebeat/filebeat.yml:/filebeat.yml
    - ./docker/filebeat/logstash-beats.crt:/etc/pki/tls/certs/logstash-beats.crt
    - ${ELROND_LOG_LOCATION}:/elogs

#networks:
#  elrond:
#    external:
#      name: "elrond"
  test:
    build: ./
