OverridableConfigTomlValues = [
   { File = "config.toml", Path = "TestConfigI8.Int8.Number", Value = 127 },
   { File = "config.toml", Path = "TestConfigI8.Int8.Number", Value = 128 },
   { File = "config.toml", Path = "TestConfigI8.Int8.Number", Value = -128 },
   { File = "config.toml", Path = "TestConfigI8.Int8.Number", Value = -129 },
   { File = "config.toml", Path = "TestConfigI16.Int16.Number", Value = 32767 },
   { File = "config.toml", Path = "TestConfigI16.Int16.Number", Value = 32768 },
   { File = "config.toml", Path = "TestConfigI16.Int16.Number", Value = -32768 },
   { File = "config.toml", Path = "TestConfigI16.Int16.Number", Value = -32769 },
   { File = "config.toml", Path = "TestConfigI32.Int32.Number", Value = 2147483647 },
   { File = "config.toml", Path = "TestConfigI32.Int32.Number", Value = 2147483648 },
   { File = "config.toml", Path = "TestConfigI32.Int32.Number", Value = -2147483648 },
   { File = "config.toml", Path = "TestConfigI32.Int32.Number", Value = -2147483649 },
   { File = "config.toml", Path = "TestConfigI64.Int64.Number", Value = 9223372036854775807 },
   { File = "config.toml", Path = "TestConfigI64.Int64.Number", Value = -9223372036854775808 },
   { File = "config.toml", Path = "TestConfigU8.Uint8.Number", Value = 255 },
   { File = "config.toml", Path = "TestConfigU8.Uint8.Number", Value = 256 },
   { File = "config.toml", Path = "TestConfigU8.Uint8.Number", Value = -256 },
   { File = "config.toml", Path = "TestConfigU16.Uint16.Number", Value = 65535 },
   { File = "config.toml", Path = "TestConfigU16.Uint16.Number", Value = 65536 },
   { File = "config.toml", Path = "TestConfigU16.Uint16.Number", Value = -65536 },
   { File = "config.toml", Path = "TestConfigU32.Uint32.Number", Value = 4294967295 },
   { File = "config.toml", Path = "TestConfigU32.Uint32.Number", Value = 4294967296 },
   { File = "config.toml", Path = "TestConfigU32.Uint32.Number", Value = -4294967296 },
   { File = "config.toml", Path = "TestConfigU64.Uint64.Number", Value = 9223372036854775807 },
   { File = "config.toml", Path = "TestConfigU64.Uint64.Number", Value = -9223372036854775808 },
   { File = "config.toml", Path = "TestConfigF32.Float32.Number", Value = 3.4 },
   { File = "config.toml", Path = "TestConfigF32.Float32.Number", Value = 3.4e+39 },
   { File = "config.toml", Path = "TestConfigF32.Float32.Number", Value = -3.4 },
   { File = "config.toml", Path = "TestConfigF32.Float32.Number", Value = -3.4e+40 },
   { File = "config.toml", Path = "TestConfigF64.Float64.Number", Value = 1.7e+308 },
   { File = "config.toml", Path = "TestConfigF64.Float64.Number", Value = -1.7e+308 },
   { File = "config.toml", Path = "TestConfigStruct.ConfigStruct.Description", Value = { Number = 11 } },
   { File = "config.toml", Path = "TestConfigStruct.ConfigStruct.Description", Value = { Nr = 222 } },
   { File = "config.toml", Path = "TestConfigStruct.ConfigStruct.Description", Value = { Number = "11" } },
   { File = "config.toml", Path = "TestConfigNestedStruct.ConfigNestedStruct", Value = { Text = "Overwritten text", Message = { Public = false, MessageDescription = [{ Text = "Overwritten Text1" }] } } },
   { File = "config.toml", Path = "TestConfigNestedStruct.ConfigNestedStruct.Message.MessageDescription", Value = [{ Text = "Overwritten Text1" }, { Text = "Overwritten Text2" }] },
   { File = "config.toml", Path = "TestMap.Map", Value = { "Key1" = { Number = 10 }, "Key2" = { Number = 11 } } },
   { File = "config.toml", Path = "TestMap.Map", Value = { "Key2" = { Number = 2 }, "Key3" = { Number = 3 } } },
   { File = "config.toml", Path = "TestArray.Strings", Value = ["x", "y", "z"] },
   { File = "config.toml", Path = "TestArray.Ints", Value = [10, 20, 30] },
   { File = "config.toml", Path = "TestArray", Value = { Strings = ["x", "y", "z"], Ints = [10, 20, 30] } },
]
