name: Build and smoke test (on MacOS)

on:
  pull_request:
    branches: [master, rc/*]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, macOS, ARM64]
    name: Build
    steps:
      - name: Set up Go 1.23.6
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.6
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
          fi

      - name: Build
        run: |
          cd ${GITHUB_WORKSPACE}/cmd/node && go build .
          cd ${GITHUB_WORKSPACE}/cmd/seednode && go build .
          cd ${GITHUB_WORKSPACE}/cmd/keygenerator && go build .
          cd ${GITHUB_WORKSPACE}/cmd/logviewer && go build .
          cd ${GITHUB_WORKSPACE}/cmd/termui && go build .

      # On GitHub, we only run the short tests.
      - name: Run tests
        run: |
          go test -short -v ./...
